version: '3.8'
services:
  video-verification-api:
    # For production, scale containers for concurrency instead of using --workers
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - whisper-model-cache:/root/.cache
      - app:/app

volumes:
  whisper-model-cache: 
  app: 